Handling Missing Data

In [1]:
import pandas as pd
import numpy as np
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
print(string_data)

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object


In [2]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [3]:
string_data[0] = None

In [4]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

Filtering Out Missing Data

In [5]:
from numpy import nan as NA

In [6]:
data = pd.Series([1, NA, 3.5, NA, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [7]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [8]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA], [NA, NA, NA], [NA, 6.5, 3.]])
cleaned = data.dropna()
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [9]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [10]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [11]:
data[4] = NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [12]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [13]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
df

0         1         2
0  0.562448       NaN       NaN
1 -1.279976       NaN       NaN
2  0.646616       NaN -1.029673
3 -0.830913       NaN -1.681558
4  0.208847 -1.348958  1.027408
5 -0.036550 -1.358900 -1.060807
6 -1.248827  0.721636  1.994478

In [14]:
df.dropna()
df.dropna(thresh=2)

0         1         2
2  0.646616       NaN -1.029673
3 -0.830913       NaN -1.681558
4  0.208847 -1.348958  1.027408
5 -0.036550 -1.358900 -1.060807
6 -1.248827  0.721636  1.994478

Filling Missing Data

In [15]:
df.fillna(0)

0         1         2
0  0.562448  0.000000  0.000000
1 -1.279976  0.000000  0.000000
2  0.646616  0.000000 -1.029673
3 -0.830913  0.000000 -1.681558
4  0.208847 -1.348958  1.027408
5 -0.036550 -1.358900 -1.060807
6 -1.248827  0.721636  1.994478

In [16]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0  0.562448  0.500000  0.000000
1 -1.279976  0.500000  0.000000
2  0.646616  0.500000 -1.029673
3 -0.830913  0.500000 -1.681558
4  0.208847 -1.348958  1.027408
5 -0.036550 -1.358900 -1.060807
6 -1.248827  0.721636  1.994478

In [17]:
_ = df.fillna(0, inplace=True)
df

0         1         2
0  0.562448  0.000000  0.000000
1 -1.279976  0.000000  0.000000
2  0.646616  0.000000 -1.029673
3 -0.830913  0.000000 -1.681558
4  0.208847 -1.348958  1.027408
5 -0.036550 -1.358900 -1.060807
6 -1.248827  0.721636  1.994478

In [18]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA
df

0         1         2
0 -0.049670  0.202428  0.511337
1  1.442592 -0.054543 -3.153512
2  0.273774       NaN  0.774174
3 -0.265391       NaN  0.114029
4  1.671628       NaN       NaN
5 -1.161134       NaN       NaN

In [19]:
df.fillna(method='ffill')

/tmp/ipykernel_8134/1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')


0         1         2
0 -0.049670  0.202428  0.511337
1  1.442592 -0.054543 -3.153512
2  0.273774 -0.054543  0.774174
3 -0.265391 -0.054543  0.114029
4  1.671628 -0.054543  0.114029
5 -1.161134 -0.054543  0.114029

In [20]:
df.fillna(method='ffill', limit=2)

/tmp/ipykernel_8134/2719175769.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', limit=2)


0         1         2
0 -0.049670  0.202428  0.511337
1  1.442592 -0.054543 -3.153512
2  0.273774 -0.054543  0.774174
3 -0.265391 -0.054543  0.114029
4  1.671628       NaN  0.114029
5 -1.161134       NaN  0.114029

In [21]:
data = pd.Series([1., NA, 3.5, NA, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

Data Transformation

In [22]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'], 'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [23]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [24]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [25]:
data['v1'] = range(7)
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [26]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

Transforming Data Using a Function or Mapping

In [27]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami', 'corned beef', 'Bacon', 'pastrami', 'honey ham', 'nova lox'], 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [28]:
lowercased = data['food'].str.lower()
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [29]:
meat_to_animal = {
 'bacon': 'pig',
 'pulled pork': 'pig',
 'pastrami': 'cow',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon'
}

In [30]:
data['animal'] = lowercased.map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [31]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

Replacing Values

In [32]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [33]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [34]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [35]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [36]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

Renaming Axis Indexes

In [37]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)), index=['Ohio', 'Colorado', 'New York'], columns=['one', 'two', 'three', 'four'])

In [38]:
transform = lambda x: x[:4].upper()
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [39]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [40]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [41]:
data.rename(index={'OHIO': 'INDIANA'}, columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [42]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

Discretization and Binning

In [43]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32] 

In [44]:
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [45]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [46]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [110]:
pd.Series(cats).value_counts()

(-2.819, -0.716]      250
(-0.716, 0.000467]    250
(0.000467, 0.678]     250
(0.678, 2.969]        250
Name: count, dtype: int64

In [48]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64, left]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [49]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [50]:
data = np.random.rand(20)
pd.cut(data, 4, precision=2)

[(0.061, 0.29], (0.75, 0.98], (0.061, 0.29], (0.29, 0.52], (0.061, 0.29], ..., (0.75, 0.98], (0.29, 0.52], (0.29, 0.52], (0.061, 0.29], (0.52, 0.75]]
Length: 20
Categories (4, interval[float64, right]): [(0.061, 0.29] < (0.29, 0.52] < (0.52, 0.75] < (0.75, 0.98]]

In [51]:
data = np.random.randn(1000) # Normally distributed
cats = pd.qcut(data, 4) # Cut into quartiles
cats

[(0.678, 2.969], (-0.716, 0.000467], (-2.819, -0.716], (0.678, 2.969], (-2.819, -0.716], ..., (-0.716, 0.000467], (0.678, 2.969], (0.000467, 0.678], (0.000467, 0.678], (0.678, 2.969]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.819, -0.716] < (-0.716, 0.000467] < (0.000467, 0.678] < (0.678, 2.969]]

In [52]:
pd.value_counts(cats)

/tmp/ipykernel_8134/1485279302.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(cats)


(-2.819, -0.716]      250
(-0.716, 0.000467]    250
(0.000467, 0.678]     250
(0.678, 2.969]        250
Name: count, dtype: int64

In [53]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(0.000467, 1.266], (-1.338, 0.000467], (-1.338, 0.000467], (1.266, 2.969], (-1.338, 0.000467], ..., (-1.338, 0.000467], (1.266, 2.969], (0.000467, 1.266], (0.000467, 1.266], (1.266, 2.969]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.819, -1.338] < (-1.338, 0.000467] < (0.000467, 1.266] < (1.266, 2.969]]

Detecting and Filtering Outliers

In [54]:
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.014125    -0.008623    -0.006305     0.041625
std       1.028709     0.995476     0.973509     1.001667
min      -3.155215    -3.470860    -2.739106    -3.004484
25%      -0.713938    -0.650986    -0.692851    -0.593176
50%      -0.082196     0.032648    -0.020256     0.035080
75%       0.691644     0.650889     0.660002     0.723579
max       3.099185     3.101755     3.308625     3.100176

In [55]:
col = data[2]
col[np.abs(col) > 3]

122    3.233154
906    3.016302
951    3.308625
Name: 2, dtype: float64

In [56]:
data[np.abs(data) > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.014181    -0.007373    -0.006863     0.041458
std       1.027618     0.990780     0.971705     1.001141
min      -3.000000    -3.000000    -2.739106    -3.000000
25%      -0.713938    -0.650986    -0.692851    -0.593176
50%      -0.082196     0.032648    -0.020256     0.035080
75%       0.691644     0.650889     0.660002     0.723579
max       3.000000     3.000000     3.000000     3.000000

In [57]:
np.sign(data).head()

0    1    2    3
0 -1.0  1.0 -1.0 -1.0
1  1.0 -1.0 -1.0  1.0
2 -1.0  1.0  1.0 -1.0
3  1.0  1.0 -1.0 -1.0
4 -1.0  1.0 -1.0  1.0

Permutation and Random Sampling

In [58]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))
sampler = np.random.permutation(5)
sampler

array([3, 1, 4, 2, 0])

In [59]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [60]:
df.take(sampler)

0   1   2   3
3  12  13  14  15
1   4   5   6   7
4  16  17  18  19
2   8   9  10  11
0   0   1   2   3

In [61]:
df.sample(n=3)

0   1   2   3
2   8   9  10  11
4  16  17  18  19
1   4   5   6   7

In [62]:
choices = pd.Series([5, 7, -1, 6, 4])
draws = choices.sample(n=10, replace=True)
draws

3    6
0    5
3    6
0    5
4    4
4    4
1    7
3    6
1    7
4    4
dtype: int64

Computing Indicator/Dummy Variables

In [63]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'], 'data1': range(6)})
In [110]: pd.get_dummies(df['key'])

a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [64]:
dummies = pd.get_dummies(df['key'], prefix='key')
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False

In [65]:
np.random.seed(12345)
values = np.random.rand(10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [66]:
values = np.random.rand(10)
values

array([0.74771481, 0.96130674, 0.0083883 , 0.10644438, 0.29870371,
       0.65641118, 0.80981255, 0.87217591, 0.9646476 , 0.72368535])

String Object Methods

In [67]:
val = 'a,b, guido'
val.split(',')

['a', 'b', ' guido']

In [68]:
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [81]:
first, second, third = pieces
first + '::' + second + '::' + third

'a::b::guido'

In [70]:
'::'.join(pieces)

'a::b::guido'

In [71]:
'guido' in val

True

In [72]:
val.index(',')

1

In [73]:
val.find(':')

-1

In [109]:
val.index(' ')

4

In [78]:
val.count(',')

2

In [79]:
val.replace(',', '::')

'a::b:: guido'

In [85]:
val.replace(',', '')

'ab guido'

Regular Expressions

In [82]:
import re
text = "foo bar\t baz \tqux"
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [86]:
regex = re.compile('\s+')
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [84]:
regex.findall(text)

[' ', '\t ', ' \t']

In [91]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'
regex = re.compile(pattern, flags=re.IGNORECASE)

In [92]:
m = regex.search(text)
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [93]:
text[m.start():m.end()]

'dave@google.com'

In [94]:
print(regex.match(text))

None


In [95]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [97]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'
regex = re.compile(pattern, flags=re.IGNORECASE)

In [98]:
m = regex.match('wesm@bright.net')
m.groups()

('wesm', 'bright', 'net')

In [99]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [100]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com



Vectorized String Functions in pandas

In [101]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com', 'Rob': 'rob@gmail.com', 'Wes': np.nan}
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [102]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [103]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [104]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [105]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [106]:
mat = data.str.match(pattern, flags=re.IGNORECASE)
mat

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [107]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object