Write programs in Python using NumPy library to do the following:
a. Compute the mean, standard deviation, and variance of a two dimensional random integer array
along the second axis.
b. Get the indices of the sorted elements of a given array.
a. B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]
c. Create a 2-dimensional array of size m x n integer elements, also print the shape, type and data
type of the array and then reshape it into nx m array, n and m are user inputs given at the run time.
d. Test whether the elements of a given array are zero, non-zero and NaN. Record the indices of
these elements in three separate arrays.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

row_mean = np.mean(arr, axis=1)
  
row1_mean = row_mean[0]
print("Mean of Row 1 is", row1_mean)
row2_mean = row_mean[1]
print("Mean of Row 2 is", row2_mean)
row3_mean = row_mean[2]
print("Mean of Row 3 is", row3_mean)

print()

row_std = np.std(arr, axis=1)

row1_std = row_std[0]
print("Standard Deviation of Row 1 is", row1_std)
row2_std = row_std[1]
print("Standard Deviation of Row 2 is", row2_std)
row3_std = row_std[2]
print("Standard Deviation of Row 3 is", row3_std)

print()

row_var = np.std(arr, axis=1)

row1_var = row_var[0]
print("Variance of Row 1 is", row1_var)
row2_var = row_var[1]
print("Variance of Row 2 is", row2_var)
row3_var = row_var[2]
print("Variance of Row 3 is", row3_var)

Mean of Row 1 is 2.0
Mean of Row 2 is 5.0
Mean of Row 3 is 8.0

Standard Deviation of Row 1 is 0.816496580927726
Standard Deviation of Row 2 is 0.816496580927726
Standard Deviation of Row 3 is 0.816496580927726

Variance of Row 1 is 0.816496580927726
Variance of Row 2 is 0.816496580927726
Variance of Row 3 is 0.816496580927726


In [2]:
import numpy as np
arr = np.array([56,48,22,41,78,91,24,46,8,33])
print(np.argsort(arr))

[8 2 6 9 3 7 1 0 4 5]


In [4]:
import numpy as np
n = int(input("Enter number of rows: "))
m = int(input("Enter number of columns: "))
arr = np.random.randint(5, size=(n,m))
print(arr)
shape = np.shape(arr)
print("Shape =", shape)
ty = type(arr)
print("Type =", ty)
data_type = arr.dtype
print("Data Type =", data_type)

l2 = arr.reshape(m,n)  
print("The matrix is: ")
print(l2)

[[2 4]
 [3 3]
 [1 1]
 [1 4]
 [3 1]]
Shape = (5, 2)
Type = <class 'numpy.ndarray'>
Data Type = int32
The matrix is: 
[[2 4 3 3 1]
 [1 1 4 3 1]]


In [12]:
arr = np.array([1, 5, 0, 3 ,np.nan])

print("Array with zero elements =", np.where(arr == 0)[0])
print("Array with non-zero elements =", np.where(arr == np.isnan)[0])
print("Array with nan elements =", np.where(arr != 0)[0])

Array with zero elements = [2]
Array with non-zero elements = []
Array with nan elements = [0 1 3 4]
